// Code generated by protoc-gen-go. DO NOT EDIT.
// source: info.proto

package information

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Param struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Param) Reset()         { *m = Param{} }
func (m *Param) String() string { return proto.CompactTextString(m) }
func (*Param) ProtoMessage()    {}
func (*Param) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{1}
}

func (m *Param) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Param.Unmarshal(m, b)
}
func (m *Param) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Param.Marshal(b, m, deterministic)
}
func (m *Param) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Param.Merge(m, src)
}
func (m *Param) XXX_Size() int {
	return xxx_messageInfo_Param.Size(m)
}
func (m *Param) XXX_DiscardUnknown() {
	xxx_messageInfo_Param.DiscardUnknown(m)
}

var xxx_messageInfo_Param proto.InternalMessageInfo

func (m *Param) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ChannelInfo struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BmsCode              string   `protobuf:"bytes,3,opt,name=bms_code,json=bmsCode,proto3" json:"bms_code,omitempty"`
	DefinitionCode       string   `protobuf:"bytes,4,opt,name=definition_code,json=definitionCode,proto3" json:"definition_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelInfo) Reset()         { *m = ChannelInfo{} }
func (m *ChannelInfo) String() string { return proto.CompactTextString(m) }
func (*ChannelInfo) ProtoMessage()    {}
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{2}
}

func (m *ChannelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelInfo.Unmarshal(m, b)
}
func (m *ChannelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelInfo.Marshal(b, m, deterministic)
}
func (m *ChannelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelInfo.Merge(m, src)
}
func (m *ChannelInfo) XXX_Size() int {
	return xxx_messageInfo_ChannelInfo.Size(m)
}
func (m *ChannelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelInfo proto.InternalMessageInfo

func (m *ChannelInfo) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ChannelInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChannelInfo) GetBmsCode() string {
	if m != nil {
		return m.BmsCode
	}
	return ""
}

func (m *ChannelInfo) GetDefinitionCode() string {
	if m != nil {
		return m.DefinitionCode
	}
	return ""
}

type BitRateInfo struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	VideoBitRate         int64    `protobuf:"varint,2,opt,name=video_bit_rate,json=videoBitRate,proto3" json:"video_bit_rate,omitempty"`
	AudioBitRate         int64    `protobuf:"varint,3,opt,name=audio_bit_rate,json=audioBitRate,proto3" json:"audio_bit_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BitRateInfo) Reset()         { *m = BitRateInfo{} }
func (m *BitRateInfo) String() string { return proto.CompactTextString(m) }
func (*BitRateInfo) ProtoMessage()    {}
func (*BitRateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{3}
}

func (m *BitRateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BitRateInfo.Unmarshal(m, b)
}
func (m *BitRateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BitRateInfo.Marshal(b, m, deterministic)
}
func (m *BitRateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitRateInfo.Merge(m, src)
}
func (m *BitRateInfo) XXX_Size() int {
	return xxx_messageInfo_BitRateInfo.Size(m)
}
func (m *BitRateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BitRateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BitRateInfo proto.InternalMessageInfo

func (m *BitRateInfo) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *BitRateInfo) GetVideoBitRate() int64 {
	if m != nil {
		return m.VideoBitRate
	}
	return 0
}

func (m *BitRateInfo) GetAudioBitRate() int64 {
	if m != nil {
		return m.AudioBitRate
	}
	return 0
}

type ChannelDetail struct {
	Code                 string         `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BmsCode              string         `protobuf:"bytes,3,opt,name=bms_code,json=bmsCode,proto3" json:"bms_code,omitempty"`
	Lang                 []string       `protobuf:"bytes,4,rep,name=lang,proto3" json:"lang,omitempty"`
	DefinitionCode       string         `protobuf:"bytes,5,opt,name=definition_code,json=definitionCode,proto3" json:"definition_code,omitempty"`
	BitRate              []*BitRateInfo `protobuf:"bytes,6,rep,name=bit_rate,json=bitRate,proto3" json:"bit_rate,omitempty"`
	InstanceName         string         `protobuf:"bytes,7,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	Drm                  string         `protobuf:"bytes,8,opt,name=drm,proto3" json:"drm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ChannelDetail) Reset()         { *m = ChannelDetail{} }
func (m *ChannelDetail) String() string { return proto.CompactTextString(m) }
func (*ChannelDetail) ProtoMessage()    {}
func (*ChannelDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{4}
}

func (m *ChannelDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelDetail.Unmarshal(m, b)
}
func (m *ChannelDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelDetail.Marshal(b, m, deterministic)
}
func (m *ChannelDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelDetail.Merge(m, src)
}
func (m *ChannelDetail) XXX_Size() int {
	return xxx_messageInfo_ChannelDetail.Size(m)
}
func (m *ChannelDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelDetail proto.InternalMessageInfo

func (m *ChannelDetail) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ChannelDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChannelDetail) GetBmsCode() string {
	if m != nil {
		return m.BmsCode
	}
	return ""
}

func (m *ChannelDetail) GetLang() []string {
	if m != nil {
		return m.Lang
	}
	return nil
}

func (m *ChannelDetail) GetDefinitionCode() string {
	if m != nil {
		return m.DefinitionCode
	}
	return ""
}

func (m *ChannelDetail) GetBitRate() []*BitRateInfo {
	if m != nil {
		return m.BitRate
	}
	return nil
}

func (m *ChannelDetail) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

func (m *ChannelDetail) GetDrm() string {
	if m != nil {
		return m.Drm
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "information.Empty")
	proto.RegisterType((*Param)(nil), "information.Param")
	proto.RegisterType((*ChannelInfo)(nil), "information.ChannelInfo")
	proto.RegisterType((*BitRateInfo)(nil), "information.bitRateInfo")
	proto.RegisterType((*ChannelDetail)(nil), "information.ChannelDetail")
}

func init() { proto.RegisterFile("info.proto", fileDescriptor_f140d5b28dddb141) }

var fileDescriptor_f140d5b28dddb141 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x41, 0x4f, 0xfa, 0x30,
	0x18, 0xc6, 0xff, 0xfc, 0x37, 0x28, 0xbc, 0x03, 0x34, 0x3d, 0x4d, 0xbc, 0x90, 0x6a, 0x22, 0xa7,
	0x1d, 0xe0, 0xe8, 0x0d, 0xf4, 0xe0, 0x41, 0x63, 0xe6, 0x07, 0x58, 0xba, 0xed, 0x05, 0x9b, 0xd0,
	0x96, 0x94, 0x4a, 0xe4, 0xb3, 0x7b, 0x31, 0x6d, 0xa7, 0x42, 0x82, 0x37, 0x6f, 0xcf, 0x9e, 0xfd,
	0xb6, 0x3e, 0xef, 0xd3, 0x17, 0x40, 0xa8, 0xa5, 0xce, 0x36, 0x46, 0x5b, 0x4d, 0x13, 0xa7, 0x8d,
	0xe4, 0x56, 0x68, 0xc5, 0x08, 0xb4, 0xef, 0xe5, 0xc6, 0xee, 0xd9, 0x25, 0xb4, 0x9f, 0xb9, 0xe1,
	0x92, 0x52, 0x88, 0x2b, 0x5d, 0x63, 0xda, 0x1a, 0xb7, 0x26, 0xbd, 0xdc, 0x6b, 0xb6, 0x87, 0x64,
	0xf1, 0xca, 0x95, 0xc2, 0xf5, 0x83, 0x5a, 0xea, 0x53, 0x88, 0xf3, 0x14, 0x97, 0x98, 0xfe, 0x0f,
	0x9e, 0xd3, 0xf4, 0x02, 0xba, 0xa5, 0xdc, 0x16, 0x9e, 0x8d, 0xbc, 0x4f, 0x4a, 0xb9, 0x5d, 0x38,
	0xfc, 0x06, 0xce, 0x6a, 0x5c, 0x0a, 0x25, 0x5c, 0x8a, 0x40, 0xc4, 0x9e, 0x18, 0xfe, 0xd8, 0x0e,
	0x64, 0x12, 0x92, 0x52, 0xd8, 0x9c, 0x5b, 0xfc, 0xf5, 0xe8, 0x6b, 0x18, 0xee, 0x44, 0x8d, 0xba,
	0x28, 0x85, 0x2d, 0x0c, 0xb7, 0x21, 0x44, 0x94, 0xf7, 0xbd, 0x3b, 0x0f, 0x5f, 0x3b, 0x8a, 0xbf,
	0xd5, 0xe2, 0x80, 0x8a, 0x02, 0xe5, 0xdd, 0x86, 0x62, 0x1f, 0x2d, 0x18, 0x34, 0xa3, 0xde, 0xa1,
	0xe5, 0x62, 0xfd, 0x17, 0xc3, 0x52, 0x88, 0xd7, 0x5c, 0xad, 0xd2, 0x78, 0x1c, 0x39, 0xdc, 0xe9,
	0x53, 0x05, 0xb4, 0x4f, 0x15, 0x40, 0x67, 0xd0, 0xfd, 0x4e, 0xdc, 0x19, 0x47, 0x93, 0x64, 0x9a,
	0x66, 0x07, 0x37, 0x98, 0x1d, 0xb4, 0x93, 0x93, 0xe6, 0x81, 0x5e, 0xc1, 0x40, 0xa8, 0xad, 0xe5,
	0xaa, 0xc2, 0xc2, 0x27, 0x25, 0xfe, 0xdf, 0xfd, 0x2f, 0xf3, 0xc9, 0x25, 0x3e, 0x87, 0xa8, 0x36,
	0x32, 0xed, 0xfa, 0x57, 0x4e, 0x4e, 0x1f, 0x61, 0xd8, 0x0c, 0xff, 0x82, 0x66, 0x27, 0x2a, 0xa4,
	0xb7, 0x40, 0x56, 0x68, 0x43, 0xf5, 0x47, 0xc7, 0xfa, 0x65, 0x19, 0x8d, 0x8e, 0xbc, 0xa3, 0xe2,
	0xd8, 0xbf, 0x79, 0x0f, 0x08, 0xbe, 0x67, 0x2b, 0xb3, 0xa9, 0xca, 0x8e, 0xdf, 0xbd, 0xd9, 0x67,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x3c, 0x20, 0xc8, 0x89, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChannelServiceClient is the client API for ChannelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChannelServiceClient interface {
	GetInfo(ctx context.Context, in *Param, opts ...grpc.CallOption) (*ChannelDetail, error)
}

type channelServiceClient struct {
	cc *grpc.ClientConn
}

func NewChannelServiceClient(cc *grpc.ClientConn) ChannelServiceClient {
	return &channelServiceClient{cc}
}

func (c *channelServiceClient) GetInfo(ctx context.Context, in *Param, opts ...grpc.CallOption) (*ChannelDetail, error) {
	out := new(ChannelDetail)
	err := c.cc.Invoke(ctx, "/information.ChannelService/getInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelServiceServer is the server API for ChannelService service.
type ChannelServiceServer interface {
	GetInfo(context.Context, *Param) (*ChannelDetail, error)
}

// UnimplementedChannelServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChannelServiceServer struct {
}

func (*UnimplementedChannelServiceServer) GetInfo(ctx context.Context, req *Param) (*ChannelDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}

func RegisterChannelServiceServer(s *grpc.Server, srv ChannelServiceServer) {
	s.RegisterService(&_ChannelService_serviceDesc, srv)
}

func _ChannelService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Param)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/information.ChannelService/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).GetInfo(ctx, req.(*Param))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChannelService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "information.ChannelService",
	HandlerType: (*ChannelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getInfo",
			Handler:    _ChannelService_GetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "info.proto",
}
